github actions practice

diff --git a/.github/workflows/example5.yml b/.github/workflows/example5.yml
--- a/.github/workflows/example5.yml
+++ b/.github/workflows/example5.yml
@@ -7,5 +7,6 @@ jobs:
     runs-on: self-hosted
     steps:
       - run: |
-          echo "::error Intentional error ::Missing semicolon"
-          exit 1
+          echo "{Terraform apply}" >> $GITHUB_STEP_SUMMARY
+#          echo "::error Intentional error ::Missing semicolon"
+#          exit 1
